#pragma once

#include "core.h"
#include <stdint.h>
#include <stdio.h>

/**
 * @file format.h
 * @brief Binary container file format (.shn) specification and header I/O
 * routines.
 *
 * @page binary_format .shn Binary File Format Specification
 * @tableofcontents
 *
 * @section format_overview 1. High-Level Format Overview
 * The `.shn` file format is a self-contained, portable binary container for
 * Shannon-compressed data generated by the `kmprs` tool.
 *
 * A `.shn` archive consists of three contiguous segments:
 * @code
 * +─────────────────────────────────────────────────────────────────────────────+
 * |                                HEADER SEGMENT | |            Fixed
 * metadata: Magic bytes, file size, symbol count K           | | (14 Bytes
 * Fixed)                              |
 * +─────────────────────────────────────────────────────────────────────────────+
 * |                         FREQUENCY DICTIONARY SEGMENT | | Active
 * symbol-to-frequency mappings (5 bytes per symbol)       | | (5 * K Bytes, K
 * in 1..256)                      |
 * +─────────────────────────────────────────────────────────────────────────────+
 * |                          COMPRESSED BITSTREAM PAYLOAD | | Variable-length
 * prefix codewords packed MSB-first into bytes      | | (Variable length,
 * ceil(total_bits / 8) bytes)             |
 * +─────────────────────────────────────────────────────────────────────────────+
 * @endcode
 *
 * @section format_memory_map 2. Byte-Level Memory Map
 * | Byte Offset | Size | Type | Field Name | Description |
 * | :--- | :--- | :--- | :--- | :--- |
 * | `0x00 - 0x03` | 4 B | `uint8_t[4]` | `magic` | Magic signature: `"SHN\x01"`
 * (`0x53, 0x48, 0x4E, 0x01`). | | `0x04 - 0x0B` | 8 B | `uint64_t` |
 * `original_size` | Uncompressed payload size in bytes (Little-Endian). | |
 * `0x0C - 0x0D` | 2 B | `uint16_t` | `symbol_count` | Number of active symbols
 * K (1 <= K <= 256, Little-Endian). | | `0x0E - ...` | K * 5 B | Entries |
 * `dictionary` | K records of `(uint8_t symbol, uint32_t frequency)`. | |
 * `Offset(14 + 5*K) .. EOF` | Var | `uint8_t[]` | `bitstream` | Variable-length
 * prefix codes packed MSB-first. |
 *
 * @section format_fields 3. Field Specifications
 * - **Magic Identifier (`magic`, 4 bytes)**:
 *   Contains ASCII `'S'`, `'H'`, `'N'`, followed by version byte `0x01`.
 *   Enforces container identification and format version control.
 *
 * - **Original File Size (`original_size`, 8 bytes, Little-Endian)**:
 *   Stores the exact byte count of the uncompressed file.
 *   @note **Padding Disambiguation**: Entropy encoders pack variable bits into
 *   8-bit bytes, so the final byte almost always contains trailing zero
 * padding. Storing `original_size` allows the decompressor to halt immediately
 * upon decoding the exact payload size, safely ignoring trailing padding bits.
 *
 * - **Active Symbol Count (`symbol_count`, 2 bytes, Little-Endian)**:
 *   Stores the number of unique active symbols K (1 <= K <= 256).
 *   Uses `uint16_t` because a 256-symbol alphabet exceeds the capacity of
 * `uint8_t` (255).
 *
 * - **Frequency Dictionary (K * 5 bytes)**:
 *   Each entry contains:
 *   - `symbol` (`uint8_t`, 1 byte): The raw byte value (0 to 255).
 *   - `frequency` (`uint32_t`, 4 bytes, Little-Endian): Total occurrence count.
 *   Storing frequencies allows the decompressor to run the exact same
 * deterministic tree construction algorithm (`build_shannon_tree()`),
 * guaranteeing identical prefix codes without storing full tree topologies.
 *
 * @section format_endianness 4. Endianness Convention
 * All multibyte integer values (`uint16_t`, `uint32_t`, `uint64_t`) are
 * explicitly serialized in **Little-Endian** byte order (least significant byte
 * first). This ensures deterministic cross-platform compatibility across
 * x86-64, ARM64, and big-endian architectures.
 */

/**
 * @def SHN_MAGIC_0
 * @brief First byte of .shn magic signature ('S').
 */
#define SHN_MAGIC_0 'S'

/**
 * @def SHN_MAGIC_1
 * @brief Second byte of .shn magic signature ('H').
 */
#define SHN_MAGIC_1 'H'

/**
 * @def SHN_MAGIC_2
 * @brief Third byte of .shn magic signature ('N').
 */
#define SHN_MAGIC_2 'N'

/**
 * @def SHN_VERSION
 * @brief Current container format version number (1).
 */
#define SHN_VERSION 0x01

/**
 * @def SHN_FIXED_HEADER_SIZE
 * @brief Size in bytes of the fixed header portion (14 bytes).
 */
#define SHN_FIXED_HEADER_SIZE 14

/**
 * @def SHN_SYMBOL_ENTRY_SIZE
 * @brief Size in bytes of each frequency dictionary record (5 bytes).
 */
#define SHN_SYMBOL_ENTRY_SIZE 5

/**
 * @enum ShnStatus
 * @brief Status and error return codes for header parsing and serialization.
 */
typedef enum {
    SHN_OK = 0,      /**< Operation completed successfully */
    SHN_ERR_IO = -1, /**< File read/write I/O error occurred */
    SHN_ERR_INVALID_MAGIC =
        -2, /**< Magic signature mismatch (not a valid .shn file) */
    SHN_ERR_INVALID_COUNT =
        -3, /**< Active symbol count K is out of valid range (1..256) */
    SHN_ERR_TRUNCATED =
        -4, /**< Unexpected end of file encountered while reading header */
    SHN_ERR_CORRUPT_STREAM =
        -5, /**< Bitstream corrupted or inconsistent with tree */
    SHN_ERR_EMPTY_FILE = -6, /**< Source input file is empty */
} ShnStatus;

/**
 * @brief Memory representation of the fixed .shn file header.
 */
typedef struct {
    uint64_t original_size; /**< Original uncompressed file size in bytes */
    uint8_t magic[4];       /**< Magic signature: 'S', 'H', 'N', 0x01 */
    uint16_t
        symbol_count; /**< Number of active symbols in dictionary (1 to 256) */
} ShnHeader;

/**
 * @brief Memory representation of an individual symbol dictionary entry.
 */
typedef struct {
    uint8_t symbol;     /**< Raw byte value (0 to 255) */
    uint32_t frequency; /**< Occurrence count of this symbol */
} ShnSymbolEntry;

/**
 * @brief Writes the .shn container header and frequency dictionary to a file.
 *
 * Serializes the magic bytes, uncompressed payload size, active symbol count,
 * and all active symbol frequency records in Little-Endian format.
 *
 * @param out           Writable destination file stream (open in "wb" mode).
 * @param original_size Total byte count of the uncompressed source file.
 * @param table         Pointer to the populated SymbolTable containing active
 * symbols.
 * @return SHN_OK on success, or a negative ShnStatus error code on failure.
 */
int write_shn_header(FILE *out, uint64_t original_size,
                     const SymbolTable *table);

/**
 * @brief Reads and validates the .shn container header and reconstructs the
 * symbol table.
 *
 * Verifies magic signature, extracts uncompressed file size, and reads all
 * symbol-frequency records into a caller-provided SymbolTable for tree
 * reconstruction.
 *
 * @param in                 Readable source file stream (open in "rb" mode).
 * @param out_original_size  Pointer to store the uncompressed byte count.
 * @param out_table          Pointer to caller-allocated SymbolTable to
 * populate.
 * @return SHN_OK on success, or a negative ShnStatus error code on failure.
 */
int read_shn_header(FILE *in, uint64_t *out_original_size,
                    SymbolTable *out_table);
